정리 및 표현식 정리
diff --git a/example_in_the_book/src/main.rs b/example_in_the_book/src/main.rs
index 25167bf..81cccee 100644
--- a/example_in_the_book/src/main.rs
+++ b/example_in_the_book/src/main.rs
@@ -12,8 +12,8 @@
 //!

 mod ex_0_video;
-mod rust_books;
 mod ex_tips;
+mod rust_books;

 ///
 /// # rust, 러스트
diff --git a/example_in_the_book/src/rust_books/defining_enums.rs b/example_in_the_book/src/rust_books/defining_enums.rs
index 2f33341..60f0343 100644
--- a/example_in_the_book/src/rust_books/defining_enums.rs
+++ b/example_in_the_book/src/rust_books/defining_enums.rs
@@ -12,7 +12,7 @@
 //! - 열거형 예시 `std::option::Option`
 //!     - [`option_enums`]
 //!
-
+#[allow(dead_code)]
 pub fn main() {
     enums_basic();
     enums_varients();
@@ -145,13 +145,14 @@ fn defined_message_as_enum() {
 ///
 /// 있는지 확인할 때 처리할 경우의 수를 다 따져 봤는지 컴파일러가 알려줌.
 ///
-/// null 개념 밴됨.
+/// null 개념을 다르게 구현함.
 ///
 /// ### 근데 비슷한 개념이 Option에 있긴하다
 /// 하지만 이 None이 null과 다른건, 컴파일러에서 다루는 방식이 차이가 있다
 /// option은 None이 될 수 있다는 경고를 컴파일러에서 받음
 ///
-/// 관련된 메서드도 많다.
+/// 관련된 메서드도 많다. 참고해서 활용하기
+/// None, T 두 경우를 다루기 위한 도구 match 표현식 존재
 ///
 #[allow(unused)]
 fn option_enums() {
@@ -167,6 +168,7 @@ fn option_enums() {
     let five: i32 = 5;
     let absent_number: std::option::Option<i32> = Some(4);
     // 일단은 다른 타입, 같다고 무심코 작성하는 걸 방지함
+    // let sum = five + absent_number;
     // 널 체크를 언어적으로 의식하게 해줌.
     let sum = match absent_number {
         None => five,
diff --git a/example_in_the_book/src/rust_books/expression_match.rs b/example_in_the_book/src/rust_books/expression_match.rs
new file mode 100644
index 0000000..faafd80
--- /dev/null
+++ b/example_in_the_book/src/rust_books/expression_match.rs
@@ -0,0 +1,120 @@
+//! ## match 표현식
+//!
+//!
+
+pub fn main() {
+    println!("{} wow", value_in_cents(Coin::random_coin()));
+    println!("{} wow us coin", value_in_us_cents(USCoin::random_coin()));
+}
+
+/// ## `match`, 제어 흐름 연산자
+/// 일련의 패턴들에 따라 값을 비교한 뒤, 어떤 패턴에 매칭되었는지를 바탕으로 코드를 수행하도록 해줌.
+/// - 패턴은 리터럴 값, 변수명, 와일드카드등 여러 방법이 존재, 18장에서 상세하게 나올 예정
+///
+/// 패턴을 사용과 더불어 컴파일러가 가능한 모든 경우가 처리되는 지 검사함.
+///
+#[allow(dead_code)]
+struct OverviewMatchExpression;
+
+/// 예시용 동전
+#[derive(Copy, Clone, PartialEq)]
+enum Coin {
+    Penny,
+    Nickel,
+    Dime,
+    Quarter,
+}
+
+impl Coin {
+    ///
+    ///
+    /// 추상화된 함수가 있나?
+    /// fn random_init<enum_like T>() -> Self {
+    ///     T::members.choose(&mut thread_rng).unwrap()
+    /// }
+    ///
+    fn random_coin() -> Self {
+        use rand::prelude::*;
+        match thread_rng().gen_range(0..4) {
+            0 => Coin::Penny,
+            1 => Coin::Nickel,
+            2 => Coin::Dime,
+            3 => Coin::Quarter,
+            _ => panic!("out of range!"),
+        }
+    }
+}
+
+/// ### 동전을 이용한 예시
+/// 동전 받아서 바꾸기
+///
+/// `match`의 특징
+/// - `match` 뒤에 표현식따라 옴. 어떤 값이 오든 상관없음.
+/// - 내부에서는 패턴과 코드로 이루어진 갈래가 존재.
+///     - 각 갈래는 쉼표로 구분
+/// - 순차적으로 패턴과 비교하다가 값이 패턴과 매칭되면 코드를 실행함.
+///     - 코드를 코드 블럭으로 변경 가능
+fn value_in_cents(coin: Coin) -> u8 {
+    match coin {
+        Coin::Penny => 1,
+        Coin::Nickel => {
+            println!("니켈 ㅇㅇ");
+            5
+        }
+        Coin::Dime => 10,
+        Coin::Quarter => 25,
+    }
+}
+
+/// 예시용 미국 주들
+#[derive(Debug)]
+enum UsState {
+    Alabama,
+    Alaska,
+}
+
+impl UsState {
+    fn random_state() -> Self {
+        use rand::prelude::*;
+        match thread_rng().gen_range(0..2) {
+            0 => UsState::Alabama,
+            1 => UsState::Alaska,
+            _ => panic!("out of range!"),
+        }
+    }
+}
+
+/// 예시용 미국 동전
+enum USCoin {
+    Penny,
+    Nickel,
+    Dime,
+    Quarter(UsState),
+}
+
+impl USCoin {
+    fn random_coin() -> Self {
+        use rand::prelude::*;
+        match thread_rng().gen_range(0..4) {
+            0 => USCoin::Penny,
+            1 => USCoin::Nickel,
+            2 => USCoin::Dime,
+            3 => USCoin::Quarter(UsState::random_state()),
+            _ => panic!("out of range!"),
+        }
+    }
+}
+
+/// ### 값을 바인딩 하는 예시
+///
+fn value_in_us_cents(us_coin: USCoin) -> u8 {
+    match us_coin {
+        USCoin::Penny => 1,
+        USCoin::Nickel => 5,
+        USCoin::Dime => 10,
+        USCoin::Quarter(state) => {
+            println!("what states make this? {:?}", state);
+            25
+        }
+    }
+}
diff --git a/example_in_the_book/src/rust_books/mod.rs b/example_in_the_book/src/rust_books/mod.rs
index a6426ec..1d1fc46 100644
--- a/example_in_the_book/src/rust_books/mod.rs
+++ b/example_in_the_book/src/rust_books/mod.rs
@@ -20,8 +20,10 @@
 //!
 //! 6. 열거형
 //!     - [`defining_enums`]
+//!     - [`expression_match`]
 //!
 pub mod defining_enums;
+pub mod expression_match;
 pub mod number_game;
 pub mod the_background_knowledge;
 pub mod the_defining_structs;
@@ -35,5 +37,5 @@ pub mod the_slice;

 #[allow(dead_code)]
 pub fn main() {
-    the_marcos::main();
+    expression_match::main();
 }
diff --git a/example_in_the_book/src/rust_books/the_defining_structs.rs b/example_in_the_book/src/rust_books/the_defining_structs.rs
index c5f19ad..3bae4da 100644
--- a/example_in_the_book/src/rust_books/the_defining_structs.rs
+++ b/example_in_the_book/src/rust_books/the_defining_structs.rs
@@ -115,7 +115,7 @@ fn example_of_struct_like() {
     #[allow(unused_variables)]
     let sign = Off;

-    println!("{:?}", origin.0);
+    println!("{:?}, {:?}", origin.0, origin.1);
 }

 ///
diff --git a/example_in_the_book/src/rust_books/the_mutability_shadowing.rs b/example_in_the_book/src/rust_books/the_mutability_shadowing.rs
index 1c5693d..8c287f2 100644
--- a/example_in_the_book/src/rust_books/the_mutability_shadowing.rs
+++ b/example_in_the_book/src/rust_books/the_mutability_shadowing.rs
@@ -50,7 +50,7 @@ fn immutable_variable() {

 /// 컴파일러가 오류를 출력함
 ///
-/// error[E0384]: cannot assign twice to immutable variable `immutable`
+/// error\[E0384]: cannot assign twice to immutable variable `immutable`
 /// --> src/chap/the_mutability_shadowing.rs:29:5
 ///    |
 /// 26 |     let immutable = 5;